language: c

sudo: false

env: PYTHONDONTWRITEBYTECODE=x

os:
    - linux

branches:
  only:
    - "master"

cache:
    apt: true
    directories:
        - $HOME/.runtimes
        - $HOME/.venv
        - $HOME/.cache/pip
        - $HOME/wheelhouse
        - $HOME/.stack
        - $HOME/.local

env:
    global:
        - BUILD_RUNTIMES=$HOME/.runtimes
        - FORMAT_ALL=true


jobs:
    # Prechecks that we want to run first.
    - stage: precheck
      env: TASK=check-pyup-yml
    - env: TASK=check-release-file
    - env: TASK=check-shellcheck
    - env: TASK=check-secrets
    - env: TASK=documentation
    - env: TASK=lint
    - env: TASK=doctest
    - env: TASK=check-rst
    - env: TASK=check-format
    - env: TASK=check-type-hints
    - env: TASK=check-requirements

    - stage: main
      env: TASK=check-coverage
    - env: TASK=check-pypy
    - env: TASK=check-py27
    - env: TASK=check-py36
    - env: TASK=check-quality

    # Less important tests that will probably
    # pass whenever the above do but are still
    # worth testing.
    - stage: extras
    - env: TASK=check-unicode
    - env: TASK=check-pure-tracer
    - env: TASK=check-py27-typing
    - env: TASK=check-py34
    - env: TASK=check-py35
    - env: TASK=check-nose
    - env: TASK=check-pytest28
    - env: TASK=check-faker070
    - env: TASK=check-faker-latest
    - env: TASK=check-django20
    - env: TASK=check-django111
    - env: TASK=check-pandas19
    - env: TASK=check-pandas20
    - env: TASK=check-pandas21
    - env: TASK=check-pandas22

    - stage: deploy
      env: TASK=deploy

script:
    - ./build.sh

matrix:
    fast_finish: true

notifications:
  email:
    recipients:
      - david@drmaciver.com
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
      - libgmp-dev
